# rolebinding.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: crontab-controller-rb
  namespace: default
subjects:
  - kind: ServiceAccount
    name: crontab-controller-sa
    namespace: default
roleRef:
  kind: Role
  name: crontab-controller-role
  apiGroup: rbac.authorization.k8s.io

