apiVersion: v1
kind: Pod
metadata:
  name: badpod
  labels:
    app: badpod
spec:
  containers:
  - name: nginx
    image: nginx:alpine
    resources:
      requests:
        memory: "64Mi"
        cpu: "50m"
      limits:
        memory: "128Mi"
        cpu: "100m"