apiVersion: apps/v1
kind: Deployment
metadata:
  name: pod-validator
  namespace: webhook-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pod-validator
  template:
    metadata:
      labels:
        app: pod-validator
    spec:
      containers:
      - name: validator
        image: devopsdktraining/pod-validator:2.0
        ports:
        - containerPort: 8443
        volumeMounts:
        - name: certs
          mountPath: /certs
          readOnly: true
        securityContext:
          runAsNonRoot: true
          runAsUser: 1000
      volumes:
      - name: certs
        secret:
          secretName: webhook-certs