apiVersion: v1
kind: ConfigMap
metadata:
  name: opa-policy
  namespace: kube-system
data:
  policy.rego: |
    package kubernetes.authz

    default allow = false

    allow {
        input.user == "system:masters"
    }

    allow {
        input.verb == "create"
        input.resource == "pods"
        input.request.object.metadata.labels.team == "devops"
    }

    allow {
        input.verb == "get"
    }

    allow {
        input.verb == "list"
    }

    allow {
        input.verb == "watch"
    }
