apiVersion: apps/v1
kind: Deployment
metadata:
  name: opa
  namespace: kube-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: opa
  template:
    metadata:
      labels:
        app: opa
    spec:
      containers:
        - name: opa
          image: openpolicyagent/opa:latest
          args:
            - "run"
            - "--server"
            - "--addr=0.0.0.0:443"
            - "--tls-cert-file=/certs/tls.crt"
            - "--tls-private-key-file=/certs/tls.key"
            - "/policies/policy.rego"
          volumeMounts:
            - name: policy
              mountPath: /policies
            - name: certs
              mountPath: /certs
      volumes:
        - name: policy
          configMap:
            name: opa-policy
        - name: certs
          secret:
            secretName: opa-tls
---
apiVersion: v1
kind: Service
metadata:
  name: opa
  namespace: kube-system
spec:
  ports:
    - port: 443
      targetPort: 443
  selector:
    app: opa
