apiVersion: v1
kind: Service
metadata:
  name: image-validator
  namespace: image-validator-demo
  labels:
    app: image-validator
spec:
  selector:
    app: image-validator
  ports:
    - port: 8443
      targetPort: 8443
      protocol: TCP
  type: ClusterIP