apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "bookstore.fullname" . }}-frontend
  labels:
    app: {{ include "bookstore.name" . }}
spec:
  replicas: {{ .Values.frontend.replicas }}
  selector:
    matchLabels:
      app: {{ include "bookstore.name" . }}-frontend
  template:
    metadata:
      labels:
        app: {{ include "bookstore.name" . }}-frontend
    spec:
      containers:
        - name: frontend
          image: {{ .Values.frontend.image }}
          ports:
            - containerPort: 80
