apiVersion: v1
kind: Service
metadata:
  name: {{ include "bookstore.fullname" . }}-frontend
  labels:
    app: {{ include "bookstore.name" . }}-frontend
spec:
  type: {{ .Values.frontend.service.type }}
  ports:
    - port: {{ .Values.frontend.service.port }}
      targetPort: 80
      protocol: TCP
      name: http
  selector:
    app: {{ include "bookstore.name" . }}-frontend
