apiVersion: v1
kind: Service
metadata:
  name: {{ include "bookstore.fullname" . }}-db
  labels:
    app: {{ include "bookstore.name" . }}-db
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.database.service.port }}
      targetPort: {{ .Values.database.service.port }}
      protocol: TCP
      name: mysql
  selector:
    app: {{ include "bookstore.name" . }}-db
