
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  selector:
    app: nginx          # Matches the Deployment Pods
  ports:
    - protocol: TCP
      port: 80          # Service port
      targetPort: 80    # Pod container port
  type: ClusterIP       # Internal only (default)
