apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: mysqls.operators.example.com
spec:
  group: operators.example.com
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                databaseName:
                  type: string
                databaseUser:
                  type: string
                storageSize:
                  type: string
                backupSchedule:
                  type: string
                mysqlVersion:
                  type: string
                  default: "8.0"
            status:
              type: object
              properties:
                phase:
                  type: string
                message:
                  type: string
                lastBackup:
                  type: string
  scope: Namespaced
  names:
    plural: mysqls
    singular: mysql
    kind: MySQL
    shortNames:
    - mysql