apiVersion: v1
kind: Service
metadata:
  name: {{ include "bookstore.fullname" . }}-backend
  labels:
    app: {{ include "bookstore.name" . }}-backend
spec:
  type: {{ .Values.backend.service.type }}
  ports:
    - port: {{ .Values.backend.service.port }}
      targetPort: {{ .Values.backend.service.port }}
      protocol: TCP
      name: http
  selector:
    app: {{ include "bookstore.name" . }}-backend
