# controller-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: crontab-controller
spec:
  replicas: 1
  selector:
    matchLabels:
      app: crontab-controller
  template:
    metadata:
      labels:
        app: crontab-controller
    spec:
      serviceAccountName: crontab-controller-sa   # 👈 REQUIRED
      containers:
      - name: controller
        image: devopsdktraining/crontab-controller:latest
        imagePullPolicy: Always
