# role.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: crontab-controller-role
  namespace: default
rules:
  - apiGroups: ["stable.deepak.com"]
    resources: ["crontabs"]
    verbs: ["get", "list", "watch"]

