apiVersion: v1
kind: Pod
metadata:
  name: init-demo
spec:
  containers:
  - name: app-container
    image: busybox
    command: ['sh', '-c', 'echo "App container started!" && sleep 3600']

  initContainers:
  - name: init-myservice
    image: busybox
    command: ['sh', '-c', 'echo "Waiting for service..."; sleep 20; echo "Service is up!"']