apiVersion: v1
kind: Pod
metadata:
  name: multi-container-demo
  labels:
    app: multi-container-demo   # 👈 Added label for Service selector
spec:
  containers:
  - name: web
    image: nginx
    ports:
    - containerPort: 80
    volumeMounts:
    - name: shared-data
      mountPath: /usr/share/nginx/html

  - name: sidecar
    image: busybox
    command: ['sh', '-c', 'echo "Hello from sidecar!" > /data/index.html; sleep 3600']
    volumeMounts:
    - name: shared-data
      mountPath: /data

  volumes:
  - name: shared-data
    emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: multi-container-svc
spec:
  selector:
    # Service selects the Pod by its label
    app: multi-container-demo
  ports:
    - name: http
      port: 80           # Service port (ClusterIP inside cluster)
      targetPort: 80     # ContainerPort of nginx
  type: ClusterIP        # Default, accessible only inside cluster
