apiVersion: v1
kind: Pod
metadata:
  name: bad-pod-latest-tag
  labels:
    app: test-pod
spec:
  containers:
  - name: nginx
    image: nginx:latest  # Blocked tag
    resources:
      requests:
        memory: "64Mi"
        cpu: "50m"
      limits:
        memory: "128Mi"
        cpu: "100m"
    securityContext:
      runAsNonRoot: true
      allowPrivilegeEscalation: false
      readOnlyRootFilesystem: true