apiVersion: v1
kind: Pod
metadata:
  name: good-pod
  labels:
    app: test-pod
spec:
  containers:
  - name: nginx
    image: nginx:1.25-alpine  # Approved registry, specific tag
    resources:
      requests:
        memory: "64Mi"
        cpu: "50m"
      limits:
        memory: "128Mi"
        cpu: "100m"
    securityContext:
      runAsNonRoot: true
      runAsUser: 1000
      allowPrivilegeEscalation: false
      readOnlyRootFilesystem: true
      capabilities:
        drop:
        - ALL